In [9]:
import numpy as np

In [11]:
a2 = np.array([[20,40],[30,60]])
print(a2)
print(type(a2))
print(a2.shape)

[[20 40]
 [30 60]]
<class 'numpy.ndarray'>
(2, 2)


In [15]:
c = np.arange(34,59)
print(c)
type(c)

[34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58]


numpy.ndarray

In [17]:
d = np.array([1.3467, 3.1545, 4.5934])
print(d)
np.around(d,2)

[1.3467 3.1545 4.5934]


array([1.35, 3.15, 4.59])

In [19]:
d = np.array([1.3467, 3.1545, 4.5934])
print(np.around(np.sqrt(d),2))

[1.16 1.78 2.14]


In [21]:
a2 =np.array([[3,4,6],[7,9,10],[4,6,12]])
a2

array([[ 3,  4,  6],
       [ 7,  9, 10],
       [ 4,  6, 12]])

In [25]:
a3 =np.array([[3,5,6],[7,3,10],[4,6,12]])
a3

array([[ 3,  5,  6],
       [ 7,  3, 10],
       [ 4,  6, 12]])

In [27]:
a3=np.array([[3,5,6],[7,3,10],[4,6,12]])
print(a3)
np.fill_diagonal(a3,0)
print(a3)

[[ 3  5  6]
 [ 7  3 10]
 [ 4  6 12]]
[[ 0  5  6]
 [ 7  0 10]
 [ 4  6  0]]


In [33]:
a4 =np.array([[3,4,6],[7,9,10],[4,6,12],[34,59,21]])
a4

array([[ 3,  4,  6],
       [ 7,  9, 10],
       [ 4,  6, 12],
       [34, 59, 21]])